### ISSUE TITLE
LAM PRO Custom scripts gon preModify $member$ contains deleted members

### ISSUE THREAD

**Issue by m-bach** [LDAPAccountManager/lam#222]
While creating a custom preModify script for groupOfNames I hit the following bug:

When I delete users from the group the $member$ wildcard will be the same as $ORIG.member$. The deleted members will still be in it.
When adding members to the group I get the expected result: the new members will be in $member$ but not in $ORIG.member$.

**Comment by gruberroland** [comment]
Please try to replace /usr/share/ldap-account-manager/lib/modules.inc with https://raw.githubusercontent.com/LDAPAccountManager/lam/develop/lam/lib/modules.inc. This should fix it.

I was not able to reproduce your error but the other way round (add showed wrong data). Anyway, it should work now.

**Comment by m-bach** [comment]
I replaced the modules.inc, but the problem is still the same.

Since you weren't able to reproduce the issue, here are the steps I took:

1. Added the following to "Custom Scripts":
     `gon preModify /home/user/test.py --member $member$ --orig_member $ORIG.member$`

2. Created a groupOfNames with one member (cn=User1,dc=example,dc=org)

3. Modified the group and added `cn=User2,dc=example,dc=org` and `cn=User3,dc=example,dc=org` to it
    I got the expected execution of the script and the following message:

    `Output of command "/home/user/test.py --member 'cn=User1,dc=example,dc=org,cn=cn=User2,dc=example,dc=org,cn=User3,dc=example,dc=org' --orig_member 'cn=User1,dc=example,dc=org'" with return code 0`

4. Modified the group again and removed `cn=User1,dc=example,dc=org` from member
    And here I get the original value for `$member$` instead of the new one
    `Output of command "/home/user/test.py --member 'cn=User1,dc=example,dc=org,cn=cn=User2,dc=example,dc=org,cn=User3,dc=example,dc=org' --org_member 'cn=User1,dc=example,dc=org,cn=cn=User2,dc=example,dc=org,cn=User3,dc=example,dc=org'" with return code 0 `

**Comment by gruberroland** [comment]
Please provide a screenshot of your server profile, active modules for group of names (3rd tab). Maybe you use a different module than my example setup.

**Comment by m-bach** [comment]
I also have "Custom Fields" active to add some extra data to the groups.
![Screenshot_2023-03-31_13-22-18](https://user-images.githubusercontent.com/88787401/229108117-718c49f0-ae49-44f8-94d8-5dae52f3d1dc.png)

**Comment by gruberroland** [comment]
Does it work without Custom Fields? Do you manage the attribute "member" with custom fields?

**Comment by m-bach** [comment]
I tried it without Custom Fields and it works as expected!
The custom fields does not do anything to the member attribute. I just use it to add some auxiliary objectClasses and some other attributes to the group. E.g. [nextcloudGroup](https://github.com/nextcloud/univention-app/blob/e3681b837a8446101796d809b8adf24ace1b6e25/nextcloud.schema#L54) and a custom schema.

So the problem seems to be some interaction between custom fields and custom scripts.

**Comment by gruberroland** [comment]
I think I was able to find the source of the issue. Please contact me at lampro@rg-se.de with your customer ID for a patch.

**Comment by m-bach** [comment]
The patch seems to have solved the issue. Thanks!
